apiVersion: v1
kind: Service
metadata:
  name: global-30x30
  namespace: biodiversity
  labels:
    app: global-30x30
spec:
  type: ClusterIP
  selector:
    app: global-30x30
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
